{
 "title": "Btms Backend",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Linking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Linked ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(btms_linking_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Links by Resource Type",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(btms_linking_resource_type, le) (btms_linking_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linking timing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(btms_service, le) (rate(btms_linking_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(btms_linking_faulted[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages In Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(messaging_memory_active[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "In Memory Bus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Incoming Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(messaging_memory_incoming_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Messages /s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(messaging_memory_incoming_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent in queue (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_memory_time_queued_milliseconds_bucket[$__rate_interval])) by (messaging_queue_name,le))  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(messaging_memory_queues_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(messaging_memory_outgoing_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Messages /s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(messaging_memory_outgoing_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Producers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } }
 ]
}